repos:
  # python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
      - id: ruff-format
  # - repo: local
  #   hooks:
  #     - id: mypy
  #       name: mypy
  #       language: system
  #       entry: .venv/bin/python -m mypy
  #       types: [python]
  #       exclude: test|node_modules
  #       require_serial: true
  # cypress
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
  # general
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: trailing-whitespace
